### PR TITLE
added more experiments

### PR DESCRIPTION
**Pull request by kyleheadley**
call the new scripts from the doc/ directory
combined bench and plot, use --onlyplot to avoid data regeneration
error bars are one standard deviation
these do not use .iter(), so sorting a vec is just vec.sort()

### CODE REVIEW

**Comment by asajeffrey** [comment]
Can you rebase? Github is telling me there's merge conflicts.

**Comment by kyleheadley** [comment]
Looks like you edited the benchmark file I deleted for a better version. Were you able to use `terminal pdf` with gnuplot? I saw a latex option I figured we'd switch to later, but `pdf` didn't work for me.

**Comment by asajeffrey** [comment]
`terminal pdf` works for me.

**Comment by asajeffrey** [comment]
I'm still getting merge commits, can you rebase?

**Comment by kyleheadley** [comment]
sorry, I'll do pull requests from a branch in the future. I'm currently editing your makefile to account for my changes

**Pull request merged**
